buildscript {
    repositories {
        // These repositories are only for Gradle plugins, put any other repositories in the repository block further below
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

apply plugin: 'org.spongepowered.mixin'

group = mod_version
version = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version

    copyIdeResources = true
    accessTransformer = file("src/main/resources/META-INF/accesstransformer.cfg")

    runs {
        client {
            workingDirectory project.file('run')

            workingDirectory project.file("run")
            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
            property "forge.logging.console.level", "debug"
            property "mixin.env.remapRefMap", "true"
            property "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"
            arg "-mixin.config=" + mod_id + ".mixins.json"
            mods {
                cosmopolitan {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', '${mod_id}'
            property "mixin.env.remapRefMap", "true"
            property "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"
            mods {
                cosmopolitan {
                    source sourceSets.main
                }
            }
        }

        gameTestServer {
            workingDirectory project.file("run")
            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
            property "forge.logging.console.level", "debug"
            property "mixin.env.remapRefMap", "true"
            property "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"
            arg "-mixin.config=" + mod_id + ".mixins.json"

            mods {
                cosmopolitan {
                    source sourceSets.main
                }
            }
        }

        data {

            workingDirectory project.file("run")
            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
            property "forge.logging.console.level", "debug"
            property "mixin.env.remapRefMap", "true"
            property "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"

            args "--mod", mod_id, "--all", "--output", file("src/generated/resources/"), "--existing", file("src/main/resources"), "--existing-mod", "blueprint"

            mods {
                cosmopolitan {
                    source sourceSets.main
                }
            }
        }
    }
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"

    config "${mod_id}.mixins.json"
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {url = "https://www.cursemaven.com"}
    maven {url = "https://maven.teamabnormals.com"}
    maven {url = "https://dvs1.progwml6.com/files/maven/" }
    maven {url = "https://modmaven.k-4u.nl" }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    implementation fg.deobf("curse.maven:architectury-api-419699:5137938")

    implementation fg.deobf("curse.maven:jade-324717:6271651")
    implementation fg.deobf("curse.maven:appleskin-248787:4770828")

    implementation fg.deobf("curse.maven:glitchcore-955399:5787839")
    implementation fg.deobf("curse.maven:serene-seasons-291874:6398227")
    implementation fg.deobf("curse.maven:tough-as-nails-246391:5815863")
    implementation fg.deobf("curse.maven:biomes-o-plenty-220318:6364065")

    implementation fg.deobf("curse.maven:abnormals-delight-442719:6057626")
    implementation fg.deobf("curse.maven:upgrade-aquatic-326895:6393133")
    implementation fg.deobf("curse.maven:neapolitan-382016:6248885")
    implementation fg.deobf("curse.maven:autumnity-365045:6151402")
    implementation fg.deobf("curse.maven:environmental-388992:6060255")
    implementation fg.deobf("curse.maven:atmospheric-362393:6248868")
    implementation fg.deobf("curse.maven:caverns-and-chasms-438005:6040957")
    implementation fg.deobf("curse.maven:berry-good-355589:5228437")
    implementation fg.deobf("curse.maven:gallery-1173553:6133771")
    implementation fg.deobf("com.teamabnormals:blueprint:1.20.1-7.1.3")

    implementation fg.deobf("curse.maven:jei-238222:6075247")
    implementation fg.deobf("curse.maven:just-enough-effect-descriptions-jeed-532286:6172935")

    implementation fg.deobf("curse.maven:zeta-968868:6312779")
    implementation fg.deobf("curse.maven:quark-243121:6312787")

    implementation fg.deobf("curse.maven:selene-499980:6693288")
    implementation fg.deobf("curse.maven:ecliptic-seasons-1118306:6730023")

    implementation fg.deobf("curse.maven:supplementaries-412082:6615104")

    implementation fg.deobf("curse.maven:create-328085:6323270")

    implementation fg.deobf("curse.maven:ars-nouveau-401955:6688854")
    implementation fg.deobf("curse.maven:curios-309927:5367944")
    implementation fg.deobf("curse.maven:patchouli-306770:4966125")
    implementation fg.deobf("curse.maven:geckolib-388172:5460309")

    implementation fg.deobf("curse.maven:habitat-422972:5293408")
    implementation fg.deobf("curse.maven:windsweptmod-636321:7088921")
    implementation fg.deobf("curse.maven:enlightend-502786:4880586")

    implementation fg.deobf("curse.maven:exquisito-859262:6586448")
    implementation fg.deobf("curse.maven:seasonals-416471:6058164")
    implementation fg.deobf("curse.maven:peculiars-418551:6058169")
    implementation fg.deobf("curse.maven:respiteful-836471:5563825")
    implementation fg.deobf("curse.maven:cookielicious-409577:6415811")

    implementation fg.deobf("curse.maven:farmers-delight-398521:8007609")
    implementation fg.deobf("curse.maven:brewin-and-chewin-637808:6237884")
    implementation fg.deobf("curse.maven:delightful-637529:6988183")
    implementation fg.deobf("curse.maven:collectors-reap-807101:7187709")
    implementation fg.deobf("curse.maven:casualness-delight-909519:5181805")
    implementation fg.deobf("curse.maven:frycooks-delight-1081410:5630141")
    implementation fg.deobf("curse.maven:farmers-respite-551453:5543547")
    implementation fg.deobf("curse.maven:seed-delight-1016377:5734725")
    implementation fg.deobf("curse.maven:windswept-delights-1372501:7150782")
    implementation fg.deobf("curse.maven:delighto-flight-1347014:7530249")
    implementation fg.deobf("curse.maven:youkais-homecoming-957437:8004757")
    implementation fg.deobf("curse.maven:frights-delight-927591:7366955")
    implementation fg.deobf("curse.maven:my-nethers-delight-1003673:6529919")

    implementation fg.deobf("curse.maven:vanilla-cookbook-402659:6435382")
    implementation fg.deobf("curse.maven:kitchen-karrot-880555:4936114")

    implementation fg.deobf("curse.maven:star-meow-craft-1154807:8155046")

    implementation fg.deobf("curse.maven:the-twilight-forest-227639:5468648")
    implementation fg.deobf("curse.maven:twilights-flavors-delight-871735:8004066")

    implementation fg.deobf("curse.maven:the-undergarden-379849:5182632")

    implementation fg.deobf("curse.maven:enigmatic-legacy-336184:5600004")
    implementation fg.deobf("curse.maven:caelus-308989:5281700")

    implementation fg.deobf("curse.maven:elysium-api-1158628:6589093")
    implementation fg.deobf("curse.maven:jadens-nether-expansion-1111833:6729020")
    implementation fg.deobf("curse.maven:gardens-of-the-dead-683174:7309542")

    implementation fg.deobf("curse.maven:epherolib-885449:4889101")
    implementation fg.deobf("curse.maven:croptopia-415438:4997459")

    implementation fg.deobf("curse.maven:ferritecore-429235:4810975")

    implementation fg.deobf("curse.maven:citadel-331936:7476570")
    implementation fg.deobf("curse.maven:alexs-caves-924854:5848216")

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
// When "copyIdeResources" is enabled, this will also run before the game launches in IDE environments.
// See https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html
tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version: forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors: mod_authors, mod_description: mod_description,
    ]

    inputs.properties replaceProperties

    exclude('.cache/**')

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}
// Example for how to get properties into the manifest for reading at runtime.
tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                "Specification-Title": mod_id,
                "Specification-Vendor": mod_authors,
                "Specification-Version": "1", // We are version 1 of ourselves
                "Implementation-Title": project.name,
                "Implementation-Version": project.jar.archiveVersion,
                "Implementation-Vendor": mod_authors,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

    // This is the preferred method to reobfuscate your jar file
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}
